services:
  - type: web
    name: steam-checker-auth
    runtime: node
    rootDir: steam-auth-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PUBLIC_ORIGIN
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: STEAM_API_KEY
        sync: false
